services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:12345@db:5432/cnn
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: cnn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alembic:
    build: .
    command: /root/.local/bin/poetry run alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:12345@db:5432/cnn


volumes:
  postgres_data:
