name: Sync main to RAG_Application on merge

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

    
      - name: Set Git config
        run: |
          git config user.name "GajendraGammaEdge"
          git config user.email "gajendra.patidar@gammaedge.io"

      - name: Check if last commit is a merge
        id: check_merge
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" != Merge* ]]; then
            echo "Last commit is NOT a merge commit. Exiting."
            exit 0
          fi
          echo "Merge commit detected."

      - name: Add target repository
        run: |
            git remote add target https://x-access-token:${{secrets.PERSONAL_ACCESS_TOKEN_GIT}}@github.com/GajendraGammaEdge/RAG_Application.git

      - name: Push main branch to RAG_Application
        run: |
          git push target main --force-with-lease



